//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETBWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductManager
    {
        public int ProductManagerSK { get; set; }
        public string ProductManager1 { get; set; }
    }
}
