//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETBWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductSK { get; set; }
        public string StockCode { get; set; }
        public string Description { get; set; }
        public string Brand { get; set; }
        public string Segment { get; set; }
        public string BasicSKU { get; set; }
        public string ProductManager { get; set; }
        public string ProductClass { get; set; }
        public string ProductClassDesc { get; set; }
        public string SupplierPartNumber { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentNumber { get; set; }
        public string CountryCode { get; set; }
        public Nullable<decimal> PalletQty { get; set; }
        public string FinishedGoodFlag { get; set; }
        public Nullable<decimal> EconomicBatchQty { get; set; }
        public Nullable<System.DateTime> DateSKUAdded { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string ABCCode { get; set; }
        public Nullable<System.DateTime> FirstSalesOrderDate { get; set; }
        public Nullable<decimal> FirstSalesOrderQty { get; set; }
        public string FirstSalesOrderCust { get; set; }
        public Nullable<System.DateTime> LastSalesOrderDate { get; set; }
        public Nullable<decimal> LastSalesOrderQty { get; set; }
        public string LastSalesOrderCust { get; set; }
        public Nullable<System.DateTime> LastInvoiceDate { get; set; }
        public Nullable<decimal> LastInvoiceQty { get; set; }
        public string LastInvoiceCust { get; set; }
        public Nullable<bool> AuditIsInferred { get; set; }
        public Nullable<decimal> ConvFactAltUom { get; set; }
        public Nullable<System.DateTime> FirstInvoiceDate { get; set; }
        public Nullable<decimal> FirstInvoiceQty { get; set; }
        public string FirstInvoiceCust { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContact { get; set; }
        public Nullable<System.DateTime> LastPOEntryDate { get; set; }
    }
}
